name: gps_map_camera_pro
description: GPS Map Camera Pro - Capture photos with GPS location overlay
publish_to: 'none'
version: 1.0.2+3

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6

  # Maps & Location
  google_maps_flutter: ^2.5.3
  geolocator: ^10.1.0
  geocoding: ^2.1.1

  # Camera
  camera: ^0.10.5+5

  # Permissions
  permission_handler: ^11.1.0

  # State Management
  provider: ^6.1.1

  # Utilities
  intl: ^0.19.0
  path_provider: ^2.1.2
  http: ^1.2.0
  gal: ^2.3.0
  share_plus: ^7.2.2
  shared_preferences: ^2.3.0
  image: ^4.1.7
  image_cropper: ^12.0.0
  flutter_exif_rotation: ^0.5.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  flutter_launcher_icons: ^0.13.1

flutter_launcher_icons:
  android: "ic_launcher"
  ios: false
  image_path: "play_store_icon_512.png"
  min_sdk_android: 21
  adaptive_icon_background: "#1A1A2E"
  adaptive_icon_foreground: "play_store_icon_512.png"
  web:
    generate: false

flutter:
  uses-material-design: true
